APP_NAME: Bridges in Wroclaw
SECRET_KEY: SECRET
BLOG_PREFIX: "/blog"
USE_WWW: False
DB:
  TYPE: json_file
  PATH: e2e_test_data.json

#TODO this should not be necessary argument
LANGUAGES:
  en:
    name: English
    flag: gb
    country: GB
  pl:
    name: polski
    flag: pl
    country: PL

FEATURE_FLAGS:
  USE_LAZY_LOADING: True
  SHOW_ACCESSIBILITY_TABLE: True

GOODMAP_FRONTEND_LIB_URL: "https://cdn.jsdelivr.net/npm/@problematy/goodmap@1.0.0"
